[project]
name = "byebye_predictor"
version = "0.1.0"
description = "Hybrid Telco churn prediction with ML & Spanish NLP"
authors = [
    {name = "Flavio Aguirre", email = "flavio.aguirre.dev@gmail.com"}
]
license = {text = "LicenseRef-FlavioAguirre-Proprietary"}
readme = "README.md"
requires-python = ">=3.12,<4.0"
keywords = ["churn", "sentiment analysis", "telecom", "machine learning"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "pandas",
    "numpy",
    "scikit-learn",
    "nltk",
    "joblib",
    "requests",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = ["tests"]

pythonpath = [
    "."
]

filterwarnings = [
    "ignore:.*vert.*:PendingDeprecationWarning",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
