# ========================================================================
# pytest.ini
# ========================================================================

# Configuration file for pytest
# This file specifies the directories to search for tests, the naming conventions for test files and functions
# and adds the root directory to sys.path for module imports.
# It is used to ensure that pytest can discover and run tests correctly.

[pytest]

#Test directories
testpaths = tests

# Prefixes for test files
python_files = test_*.py

# Prefixes for test functions
python_functions = test_*

# Add the root directory (where src/ is) to sys.path
pythonpath = .